# Generated by Django 3.2.6 on 2021-08-24 18:41

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='File Format')),
                ('ext', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Spatial Data File Type',
            },
        ),
        migrations.CreateModel(
            name='SpatialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='spatial_data/%Y/%m/%d')),
                ('short_description', models.CharField(max_length=200, verbose_name='Short Description')),
                ('description', models.TextField()),
                ('terms_of_use', models.TextField()),
                ('sharing', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=20)),
                ('slug', models.SlugField(editable=False, max_length=500)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('fileType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.filetype')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Spatial Data Repository',
                'verbose_name_plural': 'Spatial Data Repository',
            },
        ),
    ]
