# Generated by Django 3.2.6 on 2021-08-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetype',
            name='ext',
            field=models.CharField(max_length=10),
        ),
    ]
