# Generated by Django 3.2.6 on 2021-09-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleAddressGeocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('html_map', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Single Address Geocodes',
            },
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
