# Generated by Django 3.2.6 on 2021-09-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0002_auto_20210903_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReverseGeocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('html_map', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Reverse Geocoded coordinates',
            },
        ),
    ]
