# Generated by Django 3.2.6 on 2021-09-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0003_reversegeocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reversegeocode',
            name='lat',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reversegeocode',
            name='lon',
            field=models.CharField(max_length=200),
        ),
    ]
