# Generated by Django 3.2.6 on 2021-08-28 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRS',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('details', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Coordinate Reference Systems',
            },
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_name', models.CharField(blank=True, max_length=200, null=True)),
                ('y_start', models.FloatField()),
                ('x_start', models.FloatField()),
                ('end_name', models.CharField(blank=True, max_length=200, null=True)),
                ('y_end', models.FloatField()),
                ('x_end', models.FloatField()),
                ('distance', models.FloatField(blank=True, null=True)),
                ('direction_dd', models.FloatField(blank=True, null=True)),
                ('direction_deg', models.IntegerField(blank=True, null=True)),
                ('direction_min', models.IntegerField(blank=True, null=True)),
                ('direction_sec', models.FloatField(blank=True, null=True)),
                ('stored_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Calculated Joins',
            },
        ),
        migrations.CreateModel(
            name='Polar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(blank=True, max_length=200, null=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('distance', models.FloatField()),
                ('direction', models.CharField(max_length=200)),
                ('end_name', models.CharField(blank=True, max_length=200, null=True)),
                ('x_coordinate', models.FloatField(blank=True, null=True)),
                ('y_coordinate', models.FloatField(blank=True, null=True)),
                ('stored_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Calculated Polars',
            },
        ),
        migrations.CreateModel(
            name='CoordinateTransform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(verbose_name='X/Lon')),
                ('y', models.FloatField(verbose_name='Y/Lat')),
                ('x_trans', models.FloatField(blank=True, null=True, verbose_name='X-Transformed')),
                ('y_trans', models.FloatField(blank=True, null=True, verbose_name='Y-Transformed')),
                ('stored_on', models.DateTimeField(auto_now_add=True)),
                ('from_epsg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_epsg', to='utility.crs')),
                ('to_epsg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_epsg', to='utility.crs')),
            ],
            options={
                'verbose_name_plural': 'Coordinate Conversions',
            },
        ),
    ]
