# Generated by Django 3.2.6 on 2021-08-28 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_coordinatetransform_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinatetransform',
            name='saved',
        ),
    ]
