# Generated by Django 3.2.6 on 2021-09-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_remove_coordinatetransform_saved'),
    ]

    operations = [
        migrations.CreateModel(
            name='FromShapefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='from_shapefile')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'From-Shapefile-Conversions/%Y/%m/%d/',
            },
        ),
    ]
