# Generated by Django 3.2.6 on 2021-09-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_fromshapefile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fromshapefile',
            options={'verbose_name_plural': 'From-Shapefile-Conversions'},
        ),
        migrations.AlterField(
            model_name='fromshapefile',
            name='file',
            field=models.FileField(upload_to='from_shapefile/%Y/%m/%d/'),
        ),
    ]
