# Generated by Django 3.2.9 on 2021-11-04 15:00

from django.db import migrations, models
import utility.validators


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_auto_20210910_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fromshapefile',
            name='file',
            field=models.FileField(upload_to='from_shapefile/%Y/%m/%d/', validators=[utility.validators.validate_shapefile]),
        ),
    ]
